### ISSUE TITLE
Error: Download failed;

### ISSUE THREAD

**Issue by cls3415** [NikKrieger/sociome#11]
Hi-
I simply tried to download ADI data for VA, but I got the following errors:
Error: Download failed; check your internet connection or the status of the Census Bureau website
                 at http://www2.census.gov/geo/tiger/.

The code I used was:
va <- 
  get_adi(
    geography = "tract",
    state = "VA",
    dataset = "acs5",
    year = 2017,
    geometry = TRUE
  )

Note that, there is no problem to download NC or SC. 
Any thought?

Thanks!!

**Comment by NikKrieger** [comment]
Have you tried this again lately? It works for me.

My guess is that there was a connection problem where it failed before it was able to pull all of Virginia's counties' data. Virginia has more counties than either of the Carolinas, so it probably just never could get to pulling all of the counties before connectivity issues thwarted the data pull.

Let me know if you still have any issues. Sorry for the long delay.
