### ISSUE TITLE
Adding clarification of ADI-3's availability

### ISSUE THREAD

**Issue by kristenaberg** [NikKrieger/sociome#13]
Documentation request:

Add clarification to the README that the ADI-3 (Berg et al., 2021) has been incorporated into sociome and is now automatically provided, along with the ADI (Singh, 2003), in the output of get_adi() and calculate_adi(). This will permit users to incorporate either the global ADI or its comprising three factors into modeling efforts.

**Comment by NikKrieger** [comment]
Is this the correct link for Berg et al., 2021? https://link.springer.com/article/10.1007/s10742-021-00248-6 
And is this the best one for Singh, 2003? https://ajph.aphapublications.org/doi/full/10.2105/AJPH.93.7.1137

**Comment by kristenaberg** [comment]
Yes, those are the correct links/doi's. Thank you, Nik!
