### ISSUE TITLE
Deprecated `.subclass` argument

### ISSUE THREAD

**Issue by lionel-** [NikKrieger/sociome#14]
Hello. The `.subclass` argument of `abort()`, `warn()` and `inform()` has been renamed to `class` in rlang 0.4.2 (released in November 2019).

No rush but could you please look into renaming any occurrences of `.subclass` in your package?

https://github.com/NikKrieger/sociome/blob/087038ad905b9dd4db638de89a1ef65675958993/R/calculate_adi.R#L125

**Comment by NikKrieger** [comment]
fixed
