### ISSUE TITLE
Water-only tracts and airports are silently included

### ISSUE THREAD

**Issue by NikKrieger** [NikKrieger/sociome#3]

**Comment by NikKrieger** [comment]
@atperzynski, I had been thinking that the solution to this problem would be to somehow get a list of tracts/block groups that are known to be water or airports. 

HOWEVER: would it be better to simply filter out tracts that have a total population of zero before running `psych::principal()`? That's what really matters, right?

**Comment by atperzynski** [comment]
Filtering on population will solve for a majority. There are a handful that
will have single digits residents.

**Comment by NikKrieger** [comment]
@atperzynski, do you want to enforce a minimum population for areas to be considered? 5? 10?

**Comment by atperzynski** [comment]
I am back pedaling. Let's go with zero households as the rule. See this
publication (which is awesome for a dozen reasons). Basically, they say
remove all tracts/block groups/small areas that do not have any households.
This gives us the ability to cite their paper as the reason we did it.

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0115626

Copying Jarrod, as the heuristic optimization algorithm in this paper has
implications for use of EHR data elements to understand variation in small
areas in NEOCARE more broadly.

Adam

Adam T. Perzynski, PhD
Chief Science and Strategy Officer
Global Health Metrics
1 St Clair Ave NE
Cleveland, OH 44114
Cell: 216-509-3283

**Comment by NikKrieger** [comment]
This is fixed. Zero-household areas withheld from the PCA. They're still included in the resulting output, but they have an ADI of `NA`.
